"use client";
import { useEffect, useState } from "react";
import Header from "../../components/Header";
import "../../font.css";
import Editor, { loader } from "@monaco-editor/react";
import Footer from "../../components/Footer";
import componentConfig from "../../config/componentConfig";
import ComponentsHeader from "../../components/ComponentsHeader";
import AOS from "aos";
import "aos/dist/aos.css";
import cardData from "../../card/cardData";
import tableData from "../TableData";

import HomeCard from "../../HomePage/HomeCard";
const myCustomTheme = {
  base: "vs-dark",
  inherit: true,
  rules: [
    { token: "comment", foreground: "ffa500", fontStyle: "italic" },
    { token: "keyword", foreground: "00ff00" },
    { token: "identifier", foreground: "ffffff" },
  ],
  colors: {
    "editor.background": "#202020",
    "editor.lineHighlightBackground": "#333333",
  },
};

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function TableSort() {
  const [smScreen, setSmScreen] = useState(false);
  const [mdScreen, setMdScreen] = useState(false);
  const [lgScreen, setLgScreen] = useState(false);
  const [xlScreen, setXlScreen] = useState(true);
  const [code, setCode] = useState(false);
  const [copy, setCopy] = useState(false);
  const [reelatedComp, setRelatedComponents] = useState();
  const [fileName, setFileName] = useState("app.js");
  const [responsiveState, setResponsiveState] = useState(false);

  const [forceRender, setForceRender] = useState(false);
  const files = {
    "app.js": {
      _id: 0,
      name: "app.js",
      language: "javascript",
      value: tableData[0]?.htmlcode,
    },
    "style.css": {
      _id: 1,
      name: "style.css",
      language: "css",
      value: componentConfig[0]?.css,
    },
    "tailwind.config.js": {
      _id: 2,
      name: "tailwind.config.js",
      language: "javascript",
      value: componentConfig[0]?.tailwindcss,
    },
  };

  const file = files[fileName];

  const handleCopy = () => {
    navigator.clipboard.writeText(file.value);

    setCopy(true);
    setTimeout(() => {
      setCopy(false);
    }, 1500);
  };

  useEffect(() => {
    loader.init().then((monaco) => {
      monaco.editor.defineTheme("myCustomTheme", myCustomTheme);
      monaco.editor.setTheme("myCustomTheme");
    });
  }, []);

  const handleCode = () => {
    setCode(!code);
    setForceRender(!forceRender);
  };

  const handleScreen = (size) => {
    setResponsiveState(true);
    if (size === "sm") {
      setSmScreen(true);
      setMdScreen(false);
      setLgScreen(false);
      setXlScreen(false);
    } else if (size === "md") {
      setMdScreen(true);
      setLgScreen(false);
      setSmScreen(false);
      setXlScreen(false);
    } else if (size === "lg") {
      setLgScreen(true);
      setSmScreen(false);
      setMdScreen(false);
      setXlScreen(false);
    } else if (size === "xl") {
      setLgScreen(false);
      setSmScreen(false);
      setMdScreen(false);
      setXlScreen(true);
    }
    setForceRender(true);
  };

  const FilterCard = () => {
    // id=1
    var arr = [];
    // var idSection =1;
    cardData?.forEach((el) => {
      arr.push(el);
      // if(el._id!==idSection){
      //   console.log(el)

      // }
    });

    setRelatedComponents(arr);
  };

  useEffect(() => {
    AOS.init();
    AOS.refresh();
    FilterCard();
  }, []);
  return (
    <div className="bg-[rgb(255 255 255)]">
      <Header />
      <div className={`pt-[100px] container mx-auto px-2 sm:px-3`}>
        <ComponentsHeader
          title={`Table with sort option`}
          des={`This component create using CSS framework tailwindcss. It fully
              responsive component.`}
          section_name={`Table`}
          using_font="DM Sans, sans-serif"
        />

        <div data-aos="fade-up" className="drop-css p-2 rounded-lg pb-4  px-4">
          <div className={` `}>
            <div
              data-aos="fade-up"
              className={` grid lge:grid-cols-2 lg:grid-cols-2 md:grid-cols-1 mdsm:grid-cols-1 sm:grid-cols-1`}
            >
              <div
                className={`sm:hidden md:hidden mdsm:hidden lg:flex lge:flex flex space-x-5`}
              >
                {code ? (
                  <>
                    <div className={`  text-[red] text-base`}>
                      *Kindly use Tailwind config
                    </div>
                  </>
                ) : (
                  <>
                    <div
                      onClick={() => handleScreen("sm")}
                      className={` group`}
                    >
                      <div
                        className={` p-1.5 border ${
                          smScreen ? "bg-secondary text-white" : ""
                        } border-[#ccc]  group-hover:bg-secondary  cursor-pointer  rounded-md`}
                      >
                        <svg
                          stroke="currentColor"
                          fill="currentColor"
                          stroke-width="0"
                          viewBox="0 0 16 16"
                          className={`text-1xl ${
                            smScreen ? `text-white` : ``
                          } text-textcolor  group-hover:text-white`}
                          height="1em"
                          width="1em"
                          xmlns="http://www.w3.org/2000/svg"
                        >
                          <path d="M11 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1zM5 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2z"></path>
                          <path d="M8 14a1 1 0 1 0 0-2 1 1 0 0 0 0 2"></path>
                        </svg>
                      </div>
                      <p className={` text-sm text-center `}> sm</p>
                    </div>

                    <div
                      onClick={() => handleScreen("md")}
                      className={` group`}
                    >
                      <div
                        className={` p-1.5 border  border-[#ccc]   ${
                          mdScreen ? "bg-secondary text-white" : ""
                        }  group-hover:bg-secondary  cursor-pointer  rounded-md`}
                      >
                        <svg
                          stroke="currentColor"
                          fill="currentColor"
                          stroke-width="0"
                          viewBox="0 0 16 16"
                          className={`text-1xl ${
                            mdScreen ? `text-white` : ``
                          } text-textcolor  group-hover:text-white`}
                          height="1em"
                          width="1em"
                          xmlns="http://www.w3.org/2000/svg"
                        >
                          <path d="M12 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1zM4 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2z"></path>
                          <path d="M8 14a1 1 0 1 0 0-2 1 1 0 0 0 0 2"></path>
                        </svg>
                      </div>
                      <p className={` text-sm text-center `}> md</p>
                    </div>

                    <div
                      onClick={() => handleScreen("lg")}
                      className={` group`}
                    >
                      <div
                        className={` p-1.5 border   ${
                          lgScreen ? "bg-secondary" : ""
                        }  border-[#ccc]  group-hover:bg-secondary  cursor-pointer  rounded-md`}
                      >
                        <svg
                          stroke="currentColor"
                          fill="currentColor"
                          stroke-width="0"
                          viewBox="0 0 16 16"
                          className={`text-1xl ${
                            lgScreen ? `text-white` : ``
                          } text-textcolor  group-hover:text-white`}
                          height="1em"
                          width="1em"
                          xmlns="http://www.w3.org/2000/svg"
                        >
                          <path d="M13.5 3a.5.5 0 0 1 .5.5V11H2V3.5a.5.5 0 0 1 .5-.5zm-11-1A1.5 1.5 0 0 0 1 3.5V12h14V3.5A1.5 1.5 0 0 0 13.5 2zM0 12.5h16a1.5 1.5 0 0 1-1.5 1.5h-13A1.5 1.5 0 0 1 0 12.5"></path>
                        </svg>
                      </div>
                      <p className={` text-sm text-center `}> lg</p>
                    </div>

                    <div
                      onClick={() => handleScreen("xl")}
                      className={` group`}
                    >
                      <div
                        className={` p-1.5 border    border-[#ccc]  group-hover:bg-secondary  cursor-pointer  rounded-md`}
                      >
                        <svg
                          stroke="currentColor"
                          fill="currentColor"
                          stroke-width="0"
                          viewBox="0 0 16 16"
                          class=" text-1xl  text-textcolor group-hover:text-white"
                          height="1em"
                          width="1em"
                          xmlns="http://www.w3.org/2000/svg"
                        >
                          <path d="M1.5 0A1.5 1.5 0 0 0 0 1.5v7A1.5 1.5 0 0 0 1.5 10H6v1H1a1 1 0 0 0-1 1v3a1 1 0 0 0 1 1h14a1 1 0 0 0 1-1v-3a1 1 0 0 0-1-1h-5v-1h4.5A1.5 1.5 0 0 0 16 8.5v-7A1.5 1.5 0 0 0 14.5 0zm0 1h13a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-.5.5h-13a.5.5 0 0 1-.5-.5v-7a.5.5 0 0 1 .5-.5M12 12.5a.5.5 0 1 1 1 0 .5.5 0 0 1-1 0m2 0a.5.5 0 1 1 1 0 .5.5 0 0 1-1 0M1.5 12h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1 0-1M1 14.25a.25.25 0 0 1 .25-.25h5.5a.25.25 0 1 1 0 .5h-5.5a.25.25 0 0 1-.25-.25"></path>
                        </svg>
                      </div>
                      <p className={` text-sm text-center `}> xl</p>
                    </div>
                  </>
                )}
              </div>

              <div className={` flex justify-end`}>
                <div className={` flex space-x-5`}>
                  <a
                    href="/table/table-with-sort/preview"
                    // target="_blank"
                  >
                    <div className={` group`}>
                      <div
                        className={` p-1.5 border  border-[#ccc]  group-hover:bg-secondary  cursor-pointer  rounded-md`}
                      >
                        <svg
                          stroke="currentColor"
                          fill="currentColor"
                          stroke-width="0"
                          viewBox="0 0 16 16"
                          class=" text-base text-textcolor group-hover:text-white"
                          height="1em"
                          width="1em"
                          xmlns="http://www.w3.org/2000/svg"
                        >
                          <path
                            fill-rule="evenodd"
                            d="M5.828 10.172a.5.5 0 0 0-.707 0l-4.096 4.096V11.5a.5.5 0 0 0-1 0v3.975a.5.5 0 0 0 .5.5H4.5a.5.5 0 0 0 0-1H1.732l4.096-4.096a.5.5 0 0 0 0-.707m4.344 0a.5.5 0 0 1 .707 0l4.096 4.096V11.5a.5.5 0 1 1 1 0v3.975a.5.5 0 0 1-.5.5H11.5a.5.5 0 0 1 0-1h2.768l-4.096-4.096a.5.5 0 0 1 0-.707m0-4.344a.5.5 0 0 0 .707 0l4.096-4.096V4.5a.5.5 0 1 0 1 0V.525a.5.5 0 0 0-.5-.5H11.5a.5.5 0 0 0 0 1h2.768l-4.096 4.096a.5.5 0 0 0 0 .707m-4.344 0a.5.5 0 0 1-.707 0L1.025 1.732V4.5a.5.5 0 0 1-1 0V.525a.5.5 0 0 1 .5-.5H4.5a.5.5 0 0 1 0 1H1.732l4.096 4.096a.5.5 0 0 1 0 .707"
                          ></path>
                        </svg>
                      </div>
                      <p className={` text-sm text-center `}> pre</p>
                    </div>
                  </a>
                  <div className={` group`}>
                    <a
                      href={`/File/table/TableWithSortOption.html`}
                      download="TableWithSortOption.html"
                    >
                      <div
                        className={` p-1.5 border  border-[#ccc]  group-hover:bg-secondary  cursor-pointer  rounded-md`}
                      >
                        <svg
                          stroke="currentColor"
                          fill="currentColor"
                          stroke-width="0"
                          viewBox="0 0 16 16"
                          class=" text-1xl  text-textcolor group-hover:text-white"
                          height="1em"
                          width="1em"
                          xmlns="http://www.w3.org/2000/svg"
                        >
                          <path d="M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5"></path>
                          <path d="M7.646 11.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V1.5a.5.5 0 0 0-1 0v8.793L5.354 8.146a.5.5 0 1 0-.708.708z"></path>
                        </svg>
                      </div>
                    </a>
                    <p className={` text-sm text-center `}> dow</p>
                  </div>

                  <div className={`relative group`}>
                    <div
                      onClick={() => handleCopy()}
                      className={`flex justify-center p-1.5 border  ${
                        copy ? ` bg-secondary` : ``
                      } border-[#ccc]  group-hover:bg-secondary  cursor-pointer  rounded-md`}
                    >
                      <svg
                        stroke="currentColor"
                        fill="currentColor"
                        stroke-width="0"
                        viewBox="0 0 16 16"
                        className={` text-1xl  ${
                          copy ? ` text-white` : ``
                        } text-textcolor group-hover:text-white`}
                        height="1em"
                        width="1em"
                        xmlns="http://www.w3.org/2000/svg"
                      >
                        <path
                          fill-rule="evenodd"
                          d="M4 2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2zm2-1a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1zM2 5a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1v-1h1v1a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h1v1z"
                        ></path>
                      </svg>
                    </div>
                    <p className={` text-sm text-center `}> copy</p>
                    {copy ? (
                      <div
                        data-aos="fade-up"
                        className={`  flex absolute -top-12 ${
                          file?._id === 2 ? `-left-24` : `-left-10`
                        }  drop-css  rounded-md text-sm bg-[#82bd69] py-1 px-3 text-[#13250e]  `}
                      >
                        <div>
                          {file?.name === "app.js" ? (
                            "index.html"
                          ) : (
                            <>{file?.name}</>
                          )}{" "}
                        </div>{" "}
                        <div className={` px-1`}> Copied</div>{" "}
                      </div>
                    ) : null}
                  </div>

                  <div onClick={() => handleCode()} className={` group`}>
                    <div
                      className={`flex justify-center p-1.5 border ${
                        code ? ` bg-secondary` : ``
                      }  border-[#ccc]  group-hover:bg-secondary  cursor-pointer  rounded-md`}
                    >
                      <svg
                        stroke="currentColor"
                        fill="currentColor"
                        stroke-width="0"
                        viewBox="0 0 16 16"
                        className={`text-1xl  ${
                          code ? `text-white` : ``
                        } text-textcolor group-hover:text-white`}
                        height="1em"
                        width="1em"
                        xmlns="http://www.w3.org/2000/svg"
                      >
                        <path d="M10.478 1.647a.5.5 0 1 0-.956-.294l-4 13a.5.5 0 0 0 .956.294zM4.854 4.146a.5.5 0 0 1 0 .708L1.707 8l3.147 3.146a.5.5 0 0 1-.708.708l-3.5-3.5a.5.5 0 0 1 0-.708l3.5-3.5a.5.5 0 0 1 .708 0m6.292 0a.5.5 0 0 0 0 .708L14.293 8l-3.147 3.146a.5.5 0 0 0 .708.708l3.5-3.5a.5.5 0 0 0 0-.708l-3.5-3.5a.5.5 0 0 0-.708 0"></path>
                      </svg>
                    </div>
                    <p className={` text-sm text-center `}> code</p>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div
            className={`border border-[#ccc] rounded-b-lg  pt-2 px-4 pb-4  overflow-auto`}
          >
            {code ? (
              <>
                <button
                  name="app"
                  className={` ${
                    fileName === "app.js" ? `bg-primary` : ` bg-[#f19c1c8a]`
                  }   rounded-t-lg py-2  px-4 mr-2`}
                  disabled={fileName === "app.js"}
                  onClick={() => setFileName("app.js")}
                >
                  index.html
                </button>
                <button
                  name="style"
                  className={` ${
                    fileName === "style.css" ? `bg-primary` : ` bg-[#f19c1c8a]`
                  }   rounded-t-lg py-2  px-4 mr-2`}
                  disabled={fileName === "style.css"}
                  onClick={() => setFileName("style.css")}
                >
                  style
                </button>
                <button
                  name="tailwindconfig"
                  className={` ${
                    fileName === "tailwind.config.js"
                      ? `bg-primary`
                      : ` bg-[#f19c1c8a]`
                  }   rounded-t-lg py-2  px-4 mr-2`}
                  disabled={fileName === "tailwind.config.js"}
                  onClick={() => setFileName("tailwind.config.js")}
                >
                  Tailwind config
                </button>
                <Editor
                  height="80vh"
                  // theme="vs-dark"
                  path={file.name}
                  options={{ readOnly: true }}
                  defaultLanguage={file.language}
                  defaultValue={file.value}
                />
              </>
            ) : (
              <>
                <div
                  className={` ${
                    smScreen
                      ? `  w-[640px] h-auto overflow-auto mx-auto   px-20 `
                      : `${
                          mdScreen
                            ? `  w-[780px] h-auto overflow-auto mx-auto`
                            : ` ${
                                lgScreen
                                  ? `w-[980px] h-auto overflow-auto mx-auto `
                                  : ` ${xlScreen ? `w-full` : ``} `
                              }  `
                        }`
                  } `}
                >
                  <section className={` h-[80vh] container mx-auto `}>
                    <div className={` container mx-auto`}>
                      <div className={` py-10 px-10`}>
                        <div className=" sm:w-full overflow-auto">
                          <table className={` w-full`}>
                            <thead>
                              <tr
                                className={`bg-[#e5f3ff] border border-t-[#e4ebff] border-b-[#e4ebff] border-r-[#fdfdfd00] border-l-[#fdfdfd00]`}
                              >
                                <th
                                  className={`${smScreen ? `py-4 ` : ``}  ${
                                    mdScreen ? `py-4` : ``
                                  } ${
                                    responsiveState
                                      ? ``
                                      : ` lg:w-auto lge:w-auto md:w-[60px] mdsm:w-w-[60px] sm:w-auto  lg:py-2 lge:py-2 md:py-4 mdsm:p-4  sm:py-4 `
                                  } flex text-sm font-medium leading-4.2 px-2 py-2 sm:text-xs`}
                                >
                                  S.No
                                </th>
                                <th className={`py-2  `}>
                                  <div
                                    className={` ${
                                      mdScreen ? `w-[300px]` : ``
                                    }  ${
                                      smScreen ? `w-[250px]` : ``
                                    } sm:w-[250px]  lg:auto lge:auto md:w-[300px] mdsm:w-[300px] flex px-2 `}
                                  >
                                    <div
                                      className={` sm:text-xs  text-sm font-medium leading-4.3 `}
                                    >
                                      Invoice{" "}
                                    </div>
                                    <div className={`mt-0.5 `}>
                                      <svg
                                        stroke="currentColor"
                                        fill="currentColor"
                                        stroke-width="0"
                                        viewBox="0 0 512 512"
                                        class="text-[#008cff] hover:text-[#0000ca] cursor-pointer text-[16px] mx-1 h-[8px] w-[14px]"
                                        height="1em"
                                        width="1em"
                                        xmlns="http://www.w3.org/2000/svg"
                                      >
                                        <path d="M256 217.9L383 345c9.4 9.4 24.6 9.4 33.9 0 9.4-9.4 9.3-24.6 0-34L273 167c-9.1-9.1-23.7-9.3-33.1-.7L95 310.9c-4.7 4.7-7 10.9-7 17s2.3 12.3 7 17c9.4 9.4 24.6 9.4 33.9 0l127.1-127z"></path>
                                      </svg>
                                      <svg
                                        stroke="currentColor"
                                        fill="currentColor"
                                        stroke-width="0"
                                        viewBox="0 0 512 512"
                                        class="text-[#008cff] hover:text-[#0000ca] cursor-pointer text-[16px] mx-1 h-[8px] w-[14px]"
                                        height="1em"
                                        width="1em"
                                        xmlns="http://www.w3.org/2000/svg"
                                      >
                                        <path d="M256 294.1L383 167c9.4-9.4 24.6-9.4 33.9 0s9.3 24.6 0 34L273 345c-9.1 9.1-23.7 9.3-33.1.7L95 201.1c-4.7-4.7-7-10.9-7-17s2.3-12.3 7-17c9.4-9.4 24.6-9.4 33.9 0l127.1 127z"></path>
                                      </svg>
                                    </div>
                                  </div>
                                </th>
                                <th className={`py-2  `}>
                                  <div
                                    className={`${
                                      mdScreen ? `w-[100px]` : ``
                                    }  ${smScreen ? `w-[150px]` : ``} ${
                                      responsiveState
                                        ? ``
                                        : `sm:w-[150px] lg:w-auto lge:w-[100px] md:w-[100px] mdsm:w-[150px] sm:text-xs    text-sm font-medium leading-4.3  flex px-2`
                                    }   flex px-2`}
                                  >
                                    <div
                                      className={`sm:text-xs   text-sm font-medium leading-4.3 `}
                                    >
                                      Due Date{" "}
                                    </div>
                                    <div className={`mt-0.5 `}>
                                      <svg
                                        stroke="currentColor"
                                        fill="currentColor"
                                        stroke-width="0"
                                        viewBox="0 0 512 512"
                                        class="text-[#008cff] hover:text-[#0000ca] cursor-pointer text-[16px] mx-1 h-[8px] w-[14px]"
                                        height="1em"
                                        width="1em"
                                        xmlns="http://www.w3.org/2000/svg"
                                      >
                                        <path d="M256 217.9L383 345c9.4 9.4 24.6 9.4 33.9 0 9.4-9.4 9.3-24.6 0-34L273 167c-9.1-9.1-23.7-9.3-33.1-.7L95 310.9c-4.7 4.7-7 10.9-7 17s2.3 12.3 7 17c9.4 9.4 24.6 9.4 33.9 0l127.1-127z"></path>
                                      </svg>
                                      <svg
                                        stroke="currentColor"
                                        fill="currentColor"
                                        stroke-width="0"
                                        viewBox="0 0 512 512"
                                        class="text-[#008cff] hover:text-[#0000ca] cursor-pointer text-[16px] mx-1 h-[8px] w-[14px]"
                                        height="1em"
                                        width="1em"
                                        xmlns="http://www.w3.org/2000/svg"
                                      >
                                        <path d="M256 294.1L383 167c9.4-9.4 24.6-9.4 33.9 0s9.3 24.6 0 34L273 345c-9.1 9.1-23.7 9.3-33.1.7L95 201.1c-4.7-4.7-7-10.9-7-17s2.3-12.3 7-17c9.4-9.4 24.6-9.4 33.9 0l127.1 127z"></path>
                                      </svg>
                                    </div>
                                  </div>
                                </th>
                                <th className={`py-2  `}>
                                  <div className={` flex px-2 `}>
                                    <div
                                      className={`sm:text-xs  text-sm font-medium leading-4.3 `}
                                    >
                                      Status
                                    </div>
                                    <div className={`mt-0.5 `}>
                                      <svg
                                        stroke="currentColor"
                                        fill="currentColor"
                                        stroke-width="0"
                                        viewBox="0 0 512 512"
                                        class="text-[#008cff] hover:text-[#0000ca] cursor-pointer text-[16px] mx-1 h-[8px] w-[14px]"
                                        height="1em"
                                        width="1em"
                                        xmlns="http://www.w3.org/2000/svg"
                                      >
                                        <path d="M256 217.9L383 345c9.4 9.4 24.6 9.4 33.9 0 9.4-9.4 9.3-24.6 0-34L273 167c-9.1-9.1-23.7-9.3-33.1-.7L95 310.9c-4.7 4.7-7 10.9-7 17s2.3 12.3 7 17c9.4 9.4 24.6 9.4 33.9 0l127.1-127z"></path>
                                      </svg>
                                      <svg
                                        stroke="currentColor"
                                        fill="currentColor"
                                        stroke-width="0"
                                        viewBox="0 0 512 512"
                                        class="text-[#008cff] hover:text-[#0000ca] cursor-pointer text-[16px] mx-1 h-[8px] w-[14px]"
                                        height="1em"
                                        width="1em"
                                        xmlns="http://www.w3.org/2000/svg"
                                      >
                                        <path d="M256 294.1L383 167c9.4-9.4 24.6-9.4 33.9 0s9.3 24.6 0 34L273 345c-9.1 9.1-23.7 9.3-33.1.7L95 201.1c-4.7-4.7-7-10.9-7-17s2.3-12.3 7-17c9.4-9.4 24.6-9.4 33.9 0l127.1 127z"></path>
                                      </svg>
                                    </div>
                                  </div>
                                </th>
                                <th className={`py-2  `}>
                                  <div className={` flex justify-end px-2`}>
                                    <div
                                      className={`sm:text-xs  text-sm font-medium leading-4.3 `}
                                    >
                                      Amount
                                    </div>
                                    <div className={`mt-0.5 `}>
                                      <svg
                                        stroke="currentColor"
                                        fill="currentColor"
                                        stroke-width="0"
                                        viewBox="0 0 512 512"
                                        class="text-[#008cff] hover:text-[#0000ca] cursor-pointer text-[16px] mx-1 h-[8px] w-[14px]"
                                        height="1em"
                                        width="1em"
                                        xmlns="http://www.w3.org/2000/svg"
                                      >
                                        <path d="M256 217.9L383 345c9.4 9.4 24.6 9.4 33.9 0 9.4-9.4 9.3-24.6 0-34L273 167c-9.1-9.1-23.7-9.3-33.1-.7L95 310.9c-4.7 4.7-7 10.9-7 17s2.3 12.3 7 17c9.4 9.4 24.6 9.4 33.9 0l127.1-127z"></path>
                                      </svg>
                                      <svg
                                        stroke="currentColor"
                                        fill="currentColor"
                                        stroke-width="0"
                                        viewBox="0 0 512 512"
                                        class="text-[#008cff] hover:text-[#0000ca] cursor-pointer text-[16px] mx-1 h-[8px] w-[14px]"
                                        height="1em"
                                        width="1em"
                                        xmlns="http://www.w3.org/2000/svg"
                                      >
                                        <path d="M256 294.1L383 167c9.4-9.4 24.6-9.4 33.9 0s9.3 24.6 0 34L273 345c-9.1 9.1-23.7 9.3-33.1.7L95 201.1c-4.7-4.7-7-10.9-7-17s2.3-12.3 7-17c9.4-9.4 24.6-9.4 33.9 0l127.1 127z"></path>
                                      </svg>
                                    </div>
                                  </div>
                                </th>
                                <th className={`py-2  w-[200px]  `}>
                                  <div className={`flex px-2`}>
                                    <div
                                      className={`sm:text-xs  text-sm font-medium leading-4.2 `}
                                    >
                                      Actions{" "}
                                    </div>
                                  </div>
                                </th>
                              </tr>
                            </thead>
                            <tbody>
                              <tr
                                title="TechCorp Solutions	"
                                className="border  border-b-[#ebebeb] border-t-[#fff] border-r-[#fff] border-l-[#fff]"
                              >
                                <td className="py-3 px-2 text-sm text-[#333]">
                                  {" "}
                                  001
                                </td>
                                <td className="py-3 px-2  text-sm text-[#333] font-semibold">
                                  TechCorp Solutions
                                </td>
                                <td className="py-3 px-2  text-sm text-[#333] ">
                                  22 Feb 2024
                                </td>
                                <td className="py-3 px-2  text-sm text-[#333] ">
                                  <div className="py-1 px-2 bg-[#ffa8a3] text-[#8f0700] rounded-full w-16 text-sm">
                                    Unpaid
                                  </div>
                                </td>
                                <td className="py-3 px-4  text-right text-sm text-[#333] ">
                                  $5.6
                                </td>
                                <td className="py-4 px-4  flex  space-x-12 text-sm text-[#333] ">
                                  <svg
                                    stroke="currentColor"
                                    fill="currentColor"
                                    stroke-width="0"
                                    viewBox="0 0 16 16"
                                    height="1em"
                                    width="1em"
                                    xmlns="http://www.w3.org/2000/svg"
                                    class=" text-[#008cff] hover:text-[#0000ca]  cursor-pointer delay-200 transition-all text-[16px]"
                                  >
                                    <path d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8M1.173 8a13 13 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5s3.879 1.168 5.168 2.457A13 13 0 0 1 14.828 8q-.086.13-.195.288c-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5s-3.879-1.168-5.168-2.457A13 13 0 0 1 1.172 8z"></path>
                                    <path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5M4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0"></path>
                                  </svg>

                                  <svg
                                    stroke="currentColor"
                                    fill="none"
                                    stroke-width="2"
                                    viewBox="0 0 24 24"
                                    stroke-linecap="round"
                                    stroke-linejoin="round"
                                    height="1em"
                                    width="1em"
                                    xmlns="http://www.w3.org/2000/svg"
                                    class="text-[#444] hover:text-[#0b6c00]  cursor-pointer delay-200 transition-all text-[16px]"
                                  >
                                    <path d="M12 20h9"></path>
                                    <path d="M16.5 3.5a2.121 2.121 0 0 1 3 3L7 19l-4 1 1-4L16.5 3.5z"></path>
                                  </svg>

                                  <svg
                                    stroke="currentColor"
                                    fill="currentColor"
                                    stroke-width="0"
                                    viewBox="0 0 24 24"
                                    class="text-[#444] hover:text-[#c20000]  cursor-pointer delay-200 transition-all text-[18px]"
                                    height="1em"
                                    width="1em"
                                    xmlns="http://www.w3.org/2000/svg"
                                  >
                                    <path
                                      fill="none"
                                      d="M0 0h24v24H0V0z"
                                    ></path>
                                    <path d="M6 19c0 1.1.9 2 2 2h8c1.1 0 2-.9 2-2V7H6v12zM8 9h8v10H8V9zm7.5-5-1-1h-5l-1 1H5v2h14V4z"></path>
                                  </svg>
                                </td>
                              </tr>
                              <tr
                                title="TransGlobal Logistics"
                                className="border  border-b-[#ebebeb] border-t-[#fff] border-r-[#fff] border-l-[#fff]"
                              >
                                <td className="py-3 px-2 text-sm text-[#333]">
                                  {" "}
                                  002
                                </td>
                                <td className="py-3 px-2  text-sm text-[#333] font-semibold">
                                  TransGlobal Logistics
                                </td>
                                <td className="py-3 px-2  text-sm text-[#333] ">
                                  22 Feb 2024
                                </td>
                                <td className="py-3 px-2  text-sm text-[#333] ">
                                  <div className="py-1 px-2 bg-[#b4ff8e] text-center text-[#0b6c00] rounded-full w-16">
                                    paid
                                  </div>
                                </td>
                                <td className="py-3 px-4  text-right text-sm text-[#333] ">
                                  $559.6
                                </td>
                                <td className="py-4 px-4  flex  space-x-12 text-sm text-[#333] ">
                                  <svg
                                    stroke="currentColor"
                                    fill="currentColor"
                                    stroke-width="0"
                                    viewBox="0 0 16 16"
                                    height="1em"
                                    width="1em"
                                    xmlns="http://www.w3.org/2000/svg"
                                    class=" text-[#008cff] hover:text-[#0000ca]  cursor-pointer delay-200 transition-all text-[16px]"
                                  >
                                    <path d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8M1.173 8a13 13 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5s3.879 1.168 5.168 2.457A13 13 0 0 1 14.828 8q-.086.13-.195.288c-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5s-3.879-1.168-5.168-2.457A13 13 0 0 1 1.172 8z"></path>
                                    <path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5M4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0"></path>
                                  </svg>

                                  <svg
                                    stroke="currentColor"
                                    fill="none"
                                    stroke-width="2"
                                    viewBox="0 0 24 24"
                                    stroke-linecap="round"
                                    stroke-linejoin="round"
                                    height="1em"
                                    width="1em"
                                    xmlns="http://www.w3.org/2000/svg"
                                    class="text-[#444] hover:text-[#0b6c00]  cursor-pointer delay-200 transition-all text-[16px]"
                                  >
                                    <path d="M12 20h9"></path>
                                    <path d="M16.5 3.5a2.121 2.121 0 0 1 3 3L7 19l-4 1 1-4L16.5 3.5z"></path>
                                  </svg>

                                  <svg
                                    stroke="currentColor"
                                    fill="currentColor"
                                    stroke-width="0"
                                    viewBox="0 0 24 24"
                                    class="text-[#444] hover:text-[#c20000]  cursor-pointer delay-200 transition-all text-[18px]"
                                    height="1em"
                                    width="1em"
                                    xmlns="http://www.w3.org/2000/svg"
                                  >
                                    <path
                                      fill="none"
                                      d="M0 0h24v24H0V0z"
                                    ></path>
                                    <path d="M6 19c0 1.1.9 2 2 2h8c1.1 0 2-.9 2-2V7H6v12zM8 9h8v10H8V9zm7.5-5-1-1h-5l-1 1H5v2h14V4z"></path>
                                  </svg>
                                </td>
                              </tr>
                              <tr
                                title="AquaPure Water Co."
                                className="border  border-b-[#ebebeb] border-t-[#fff] border-r-[#fff] border-l-[#fff]"
                              >
                                <td className="py-3 px-2 text-sm text-[#333]">
                                  {" "}
                                  003
                                </td>
                                <td className="py-3 px-2  text-sm text-[#333] font-semibold">
                                  AquaPure Water Co.
                                </td>
                                <td className="py-3 px-2  text-sm text-[#333] ">
                                  22 Feb 2024
                                </td>
                                <td className="py-3 px-2  text-sm text-[#333] ">
                                  <div className="py-1 px-2 bg-[#b4ff8e] text-center text-[#0b6c00] rounded-full w-16">
                                    paid
                                  </div>
                                </td>
                                <td className="py-3 px-4  text-right text-sm text-[#333] ">
                                  $785.6
                                </td>
                                <td className="py-4 px-4  flex  space-x-12 text-sm text-[#333] ">
                                  <svg
                                    stroke="currentColor"
                                    fill="currentColor"
                                    stroke-width="0"
                                    viewBox="0 0 16 16"
                                    height="1em"
                                    width="1em"
                                    xmlns="http://www.w3.org/2000/svg"
                                    class=" text-[#008cff] hover:text-[#0000ca]  cursor-pointer delay-200 transition-all text-[16px]"
                                  >
                                    <path d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8M1.173 8a13 13 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5s3.879 1.168 5.168 2.457A13 13 0 0 1 14.828 8q-.086.13-.195.288c-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5s-3.879-1.168-5.168-2.457A13 13 0 0 1 1.172 8z"></path>
                                    <path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5M4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0"></path>
                                  </svg>

                                  <svg
                                    stroke="currentColor"
                                    fill="none"
                                    stroke-width="2"
                                    viewBox="0 0 24 24"
                                    stroke-linecap="round"
                                    stroke-linejoin="round"
                                    height="1em"
                                    width="1em"
                                    xmlns="http://www.w3.org/2000/svg"
                                    class="text-[#444] hover:text-[#0b6c00]  cursor-pointer delay-200 transition-all text-[16px]"
                                  >
                                    <path d="M12 20h9"></path>
                                    <path d="M16.5 3.5a2.121 2.121 0 0 1 3 3L7 19l-4 1 1-4L16.5 3.5z"></path>
                                  </svg>

                                  <svg
                                    stroke="currentColor"
                                    fill="currentColor"
                                    stroke-width="0"
                                    viewBox="0 0 24 24"
                                    class="text-[#444] hover:text-[#c20000]  cursor-pointer delay-200 transition-all text-[18px]"
                                    height="1em"
                                    width="1em"
                                    xmlns="http://www.w3.org/2000/svg"
                                  >
                                    <path
                                      fill="none"
                                      d="M0 0h24v24H0V0z"
                                    ></path>
                                    <path d="M6 19c0 1.1.9 2 2 2h8c1.1 0 2-.9 2-2V7H6v12zM8 9h8v10H8V9zm7.5-5-1-1h-5l-1 1H5v2h14V4z"></path>
                                  </svg>
                                </td>
                              </tr>
                              <tr
                                title="VirtuaVista Entertainment	"
                                className="border  border-b-[#ebebeb] border-t-[#fff] border-r-[#fff] border-l-[#fff]"
                              >
                                <td className="py-3 px-2 text-sm text-[#333]">
                                  {" "}
                                  004
                                </td>
                                <td className="py-3 px-2  text-sm text-[#333] font-semibold">
                                  VirtuaVista Entertainment
                                </td>
                                <td className="py-3 px-2  text-sm text-[#333] ">
                                  22 Feb 2024
                                </td>
                                <td className="py-3 px-2  text-sm text-[#333] ">
                                  <div className="py-1 px-2 bg-[#ffa8a3] text-[#8f0700] rounded-full w-16 text-sm">
                                    Unpaid
                                  </div>
                                </td>
                                <td className="py-3 px-4  text-right text-sm text-[#333] ">
                                  $54.6
                                </td>
                                <td className="py-4 px-4  flex  space-x-12 text-sm text-[#333] ">
                                  <svg
                                    stroke="currentColor"
                                    fill="currentColor"
                                    stroke-width="0"
                                    viewBox="0 0 16 16"
                                    height="1em"
                                    width="1em"
                                    xmlns="http://www.w3.org/2000/svg"
                                    class=" text-[#008cff] hover:text-[#0000ca]  cursor-pointer delay-200 transition-all text-[16px]"
                                  >
                                    <path d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8M1.173 8a13 13 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5s3.879 1.168 5.168 2.457A13 13 0 0 1 14.828 8q-.086.13-.195.288c-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5s-3.879-1.168-5.168-2.457A13 13 0 0 1 1.172 8z"></path>
                                    <path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5M4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0"></path>
                                  </svg>

                                  <svg
                                    stroke="currentColor"
                                    fill="none"
                                    stroke-width="2"
                                    viewBox="0 0 24 24"
                                    stroke-linecap="round"
                                    stroke-linejoin="round"
                                    height="1em"
                                    width="1em"
                                    xmlns="http://www.w3.org/2000/svg"
                                    class="text-[#444] hover:text-[#0b6c00]  cursor-pointer delay-200 transition-all text-[16px]"
                                  >
                                    <path d="M12 20h9"></path>
                                    <path d="M16.5 3.5a2.121 2.121 0 0 1 3 3L7 19l-4 1 1-4L16.5 3.5z"></path>
                                  </svg>

                                  <svg
                                    stroke="currentColor"
                                    fill="currentColor"
                                    stroke-width="0"
                                    viewBox="0 0 24 24"
                                    class="text-[#444] hover:text-[#c20000]  cursor-pointer delay-200 transition-all text-[18px]"
                                    height="1em"
                                    width="1em"
                                    xmlns="http://www.w3.org/2000/svg"
                                  >
                                    <path
                                      fill="none"
                                      d="M0 0h24v24H0V0z"
                                    ></path>
                                    <path d="M6 19c0 1.1.9 2 2 2h8c1.1 0 2-.9 2-2V7H6v12zM8 9h8v10H8V9zm7.5-5-1-1h-5l-1 1H5v2h14V4z"></path>
                                  </svg>
                                </td>
                              </tr>
                              <tr
                                title="GreenTech Innovations"
                                className="border  border-b-[#ebebeb] border-t-[#fff] border-r-[#fff] border-l-[#fff]"
                              >
                                <td className="py-3 px-2 text-sm text-[#333]">
                                  {" "}
                                  005
                                </td>
                                <td className="py-3 px-2  text-sm text-[#333] font-semibold">
                                  GreenTech Innovations
                                </td>
                                <td className="py-3 px-2  text-sm text-[#333] ">
                                  22 Feb 2024
                                </td>
                                <td className="py-3 px-2  text-sm text-[#333] ">
                                  <div className="py-1 px-2 bg-[#b4ff8e] text-center text-[#0b6c00] rounded-full w-16">
                                    paid
                                  </div>
                                </td>
                                <td className="py-3 px-4  text-right text-sm text-[#333] ">
                                  $785.6
                                </td>
                                <td className="py-4 px-4  flex  space-x-12 text-sm text-[#333] ">
                                  <svg
                                    stroke="currentColor"
                                    fill="currentColor"
                                    stroke-width="0"
                                    viewBox="0 0 16 16"
                                    height="1em"
                                    width="1em"
                                    xmlns="http://www.w3.org/2000/svg"
                                    class=" text-[#008cff] hover:text-[#0000ca]  cursor-pointer delay-200 transition-all text-[16px]"
                                  >
                                    <path d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8M1.173 8a13 13 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5s3.879 1.168 5.168 2.457A13 13 0 0 1 14.828 8q-.086.13-.195.288c-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5s-3.879-1.168-5.168-2.457A13 13 0 0 1 1.172 8z"></path>
                                    <path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5M4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0"></path>
                                  </svg>

                                  <svg
                                    title="edit"
                                    stroke="currentColor"
                                    fill="none"
                                    stroke-width="2"
                                    viewBox="0 0 24 24"
                                    stroke-linecap="round"
                                    stroke-linejoin="round"
                                    height="1em"
                                    width="1em"
                                    xmlns="http://www.w3.org/2000/svg"
                                    class="text-[#444] hover:text-[#0b6c00]  cursor-pointer delay-200 transition-all text-[16px]"
                                  >
                                    <path d="M12 20h9"></path>
                                    <path d="M16.5 3.5a2.121 2.121 0 0 1 3 3L7 19l-4 1 1-4L16.5 3.5z"></path>
                                  </svg>

                                  <svg
                                    stroke="currentColor"
                                    fill="currentColor"
                                    stroke-width="0"
                                    viewBox="0 0 24 24"
                                    class="text-[#444] hover:text-[#c20000]  cursor-pointer delay-200 transition-all text-[18px]"
                                    height="1em"
                                    width="1em"
                                    xmlns="http://www.w3.org/2000/svg"
                                  >
                                    <path
                                      fill="none"
                                      d="M0 0h24v24H0V0z"
                                    ></path>
                                    <path d="M6 19c0 1.1.9 2 2 2h8c1.1 0 2-.9 2-2V7H6v12zM8 9h8v10H8V9zm7.5-5-1-1h-5l-1 1H5v2h14V4z"></path>
                                  </svg>
                                </td>
                              </tr>
                              <tr
                                title="Quantum Finance Corp"
                                className="border  border-b-[#ebebeb] border-t-[#fff] border-r-[#fff] border-l-[#fff]"
                              >
                                <td className="py-3 px-2 text-sm text-[#333]">
                                  {" "}
                                  006
                                </td>
                                <td className="py-3 px-2  text-sm text-[#333] font-semibold">
                                  Quantum Finance Corp
                                </td>
                                <td className="py-3 px-2  text-sm text-[#333] ">
                                  22 Feb 2024
                                </td>
                                <td className="py-3 px-2  text-sm text-[#333] ">
                                  <div className="py-1 px-2 bg-[#b4ff8e] text-center text-[#0b6c00] rounded-full w-16">
                                    paid
                                  </div>
                                </td>
                                <td className="py-3 px-4  text-right text-sm text-[#333] ">
                                  $945.6
                                </td>
                                <td className="py-4 px-4  flex  space-x-12 text-sm text-[#333] ">
                                  <svg
                                    stroke="currentColor"
                                    fill="currentColor"
                                    stroke-width="0"
                                    viewBox="0 0 16 16"
                                    height="1em"
                                    width="1em"
                                    xmlns="http://www.w3.org/2000/svg"
                                    class=" text-[#008cff] hover:text-[#0000ca]  cursor-pointer delay-200 transition-all text-[16px]"
                                  >
                                    <path d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8M1.173 8a13 13 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5s3.879 1.168 5.168 2.457A13 13 0 0 1 14.828 8q-.086.13-.195.288c-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5s-3.879-1.168-5.168-2.457A13 13 0 0 1 1.172 8z"></path>
                                    <path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5M4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0"></path>
                                  </svg>

                                  <svg
                                    stroke="currentColor"
                                    fill="none"
                                    stroke-width="2"
                                    viewBox="0 0 24 24"
                                    stroke-linecap="round"
                                    stroke-linejoin="round"
                                    height="1em"
                                    width="1em"
                                    xmlns="http://www.w3.org/2000/svg"
                                    class="text-[#444] hover:text-[#0b6c00]  cursor-pointer delay-200 transition-all text-[16px]"
                                  >
                                    <path d="M12 20h9"></path>
                                    <path d="M16.5 3.5a2.121 2.121 0 0 1 3 3L7 19l-4 1 1-4L16.5 3.5z"></path>
                                  </svg>

                                  <svg
                                    stroke="currentColor"
                                    fill="currentColor"
                                    stroke-width="0"
                                    viewBox="0 0 24 24"
                                    class="text-[#444] hover:text-[#c20000]  cursor-pointer delay-200 transition-all text-[18px]"
                                    height="1em"
                                    width="1em"
                                    xmlns="http://www.w3.org/2000/svg"
                                  >
                                    <path
                                      fill="none"
                                      d="M0 0h24v24H0V0z"
                                    ></path>
                                    <path d="M6 19c0 1.1.9 2 2 2h8c1.1 0 2-.9 2-2V7H6v12zM8 9h8v10H8V9zm7.5-5-1-1h-5l-1 1H5v2h14V4z"></path>
                                  </svg>
                                </td>
                              </tr>
                              <tr
                                title="UrbanEats Culinary Group"
                                className="border  border-b-[#ebebeb] border-t-[#fff] border-r-[#fff] border-l-[#fff]"
                              >
                                <td className="py-3 px-2 text-sm text-[#333]">
                                  {" "}
                                  007
                                </td>
                                <td className="py-3 px-2  text-sm text-[#333] font-semibold">
                                  UrbanEats Culinary Group
                                </td>
                                <td className="py-3 px-2  text-sm text-[#333] ">
                                  22 Feb 2024
                                </td>
                                <td className="py-3 px-2  text-sm text-[#333] ">
                                  <div className="py-1 px-2 bg-[#ffa8a3] text-[#8f0700] rounded-full w-16 text-sm">
                                    Unpaid
                                  </div>
                                </td>
                                <td className="py-3 px-4  text-right text-sm text-[#333] ">
                                  $40.6
                                </td>
                                <td className="py-4 px-4  flex  space-x-12 text-sm text-[#333] ">
                                  <svg
                                    stroke="currentColor"
                                    fill="currentColor"
                                    stroke-width="0"
                                    viewBox="0 0 16 16"
                                    height="1em"
                                    width="1em"
                                    xmlns="http://www.w3.org/2000/svg"
                                    class=" text-[#008cff] hover:text-[#0000ca]  cursor-pointer delay-200 transition-all text-[16px]"
                                  >
                                    <path d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8M1.173 8a13 13 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5s3.879 1.168 5.168 2.457A13 13 0 0 1 14.828 8q-.086.13-.195.288c-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5s-3.879-1.168-5.168-2.457A13 13 0 0 1 1.172 8z"></path>
                                    <path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5M4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0"></path>
                                  </svg>

                                  <svg
                                    stroke="currentColor"
                                    fill="none"
                                    stroke-width="2"
                                    viewBox="0 0 24 24"
                                    stroke-linecap="round"
                                    stroke-linejoin="round"
                                    height="1em"
                                    width="1em"
                                    xmlns="http://www.w3.org/2000/svg"
                                    class="text-[#444] hover:text-[#0b6c00]  cursor-pointer delay-200 transition-all text-[16px]"
                                  >
                                    <path d="M12 20h9"></path>
                                    <path d="M16.5 3.5a2.121 2.121 0 0 1 3 3L7 19l-4 1 1-4L16.5 3.5z"></path>
                                  </svg>

                                  <svg
                                    stroke="currentColor"
                                    fill="currentColor"
                                    stroke-width="0"
                                    viewBox="0 0 24 24"
                                    class="text-[#444] hover:text-[#c20000]  cursor-pointer delay-200 transition-all text-[18px]"
                                    height="1em"
                                    width="1em"
                                    xmlns="http://www.w3.org/2000/svg"
                                  >
                                    <path
                                      fill="none"
                                      d="M0 0h24v24H0V0z"
                                    ></path>
                                    <path d="M6 19c0 1.1.9 2 2 2h8c1.1 0 2-.9 2-2V7H6v12zM8 9h8v10H8V9zm7.5-5-1-1h-5l-1 1H5v2h14V4z"></path>
                                  </svg>
                                </td>
                              </tr>
                              <tr
                                title="NaturaLife Organics"
                                className="border  border-b-[#ebebeb] border-t-[#fff] border-r-[#fff] border-l-[#fff]"
                              >
                                <td className="py-3 px-2 text-sm text-[#333]">
                                  {" "}
                                  008
                                </td>
                                <td className="py-3 px-2  text-sm text-[#333] font-semibold">
                                  NaturaLife Organics
                                </td>
                                <td className="py-3 px-2  text-sm text-[#333] ">
                                  22 Feb 2024
                                </td>
                                <td className="py-3 px-2  text-sm text-[#333] ">
                                  <div className="py-1 px-2 text-center bg-[#b4ff8e] text-[#0b6c00] rounded-full w-16">
                                    paid
                                  </div>
                                </td>
                                <td className="py-3 px-4  text-right text-sm text-[#333] ">
                                  $715.6
                                </td>
                                <td className="py-4 px-4  flex  space-x-12 text-sm text-[#333] ">
                                  <svg
                                    stroke="currentColor"
                                    fill="currentColor"
                                    stroke-width="0"
                                    viewBox="0 0 16 16"
                                    height="1em"
                                    width="1em"
                                    xmlns="http://www.w3.org/2000/svg"
                                    class=" text-[#008cff] hover:text-[#0000ca]  cursor-pointer delay-200 transition-all text-[16px]"
                                  >
                                    <path d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8M1.173 8a13 13 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5s3.879 1.168 5.168 2.457A13 13 0 0 1 14.828 8q-.086.13-.195.288c-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5s-3.879-1.168-5.168-2.457A13 13 0 0 1 1.172 8z"></path>
                                    <path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5M4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0"></path>
                                  </svg>

                                  <svg
                                    stroke="currentColor"
                                    fill="none"
                                    stroke-width="2"
                                    viewBox="0 0 24 24"
                                    stroke-linecap="round"
                                    stroke-linejoin="round"
                                    height="1em"
                                    width="1em"
                                    xmlns="http://www.w3.org/2000/svg"
                                    class="text-[#444] hover:text-[#0b6c00]  cursor-pointer delay-200 transition-all text-[16px]"
                                  >
                                    <path d="M12 20h9"></path>
                                    <path d="M16.5 3.5a2.121 2.121 0 0 1 3 3L7 19l-4 1 1-4L16.5 3.5z"></path>
                                  </svg>

                                  <svg
                                    stroke="currentColor"
                                    fill="currentColor"
                                    stroke-width="0"
                                    viewBox="0 0 24 24"
                                    class="text-[#444] hover:text-[#c20000]  cursor-pointer delay-200 transition-all text-[18px]"
                                    height="1em"
                                    width="1em"
                                    xmlns="http://www.w3.org/2000/svg"
                                  >
                                    <path
                                      fill="none"
                                      d="M0 0h24v24H0V0z"
                                    ></path>
                                    <path d="M6 19c0 1.1.9 2 2 2h8c1.1 0 2-.9 2-2V7H6v12zM8 9h8v10H8V9zm7.5-5-1-1h-5l-1 1H5v2h14V4z"></path>
                                  </svg>
                                </td>
                              </tr>
                              <tr
                                title="AeroSpace Dynamics"
                                className="border  border-b-[#ebebeb] border-t-[#fff] border-r-[#fff] border-l-[#fff]"
                              >
                                <td className="py-3 px-2 text-sm text-[#333]">
                                  {" "}
                                  009
                                </td>
                                <td className="py-3 px-2  text-sm text-[#333] font-semibold">
                                  AeroSpace Dynamics
                                </td>
                                <td className="py-3 px-2  text-sm text-[#333] ">
                                  22 Feb 2024
                                </td>
                                <td className="py-3 px-2  text-sm text-[#333] ">
                                  <div className="py-1 px-2  text-center bg-[#b4ff8e] text-[#0b6c00] rounded-full w-16">
                                    paid
                                  </div>
                                </td>
                                <td className="py-3 px-4  text-right text-sm text-[#333] ">
                                  $625.6
                                </td>
                                <td className="py-4 px-4  flex  space-x-12 text-sm text-[#333] ">
                                  <svg
                                    stroke="currentColor"
                                    fill="currentColor"
                                    stroke-width="0"
                                    viewBox="0 0 16 16"
                                    height="1em"
                                    width="1em"
                                    xmlns="http://www.w3.org/2000/svg"
                                    class=" text-[#008cff] hover:text-[#0000ca]  cursor-pointer delay-200 transition-all text-[16px]"
                                  >
                                    <path d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8M1.173 8a13 13 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5s3.879 1.168 5.168 2.457A13 13 0 0 1 14.828 8q-.086.13-.195.288c-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5s-3.879-1.168-5.168-2.457A13 13 0 0 1 1.172 8z"></path>
                                    <path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5M4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0"></path>
                                  </svg>

                                  <svg
                                    stroke="currentColor"
                                    fill="none"
                                    stroke-width="2"
                                    viewBox="0 0 24 24"
                                    stroke-linecap="round"
                                    stroke-linejoin="round"
                                    height="1em"
                                    width="1em"
                                    xmlns="http://www.w3.org/2000/svg"
                                    class="text-[#444] hover:text-[#0b6c00]  cursor-pointer delay-200 transition-all text-[16px]"
                                  >
                                    <path d="M12 20h9"></path>
                                    <path d="M16.5 3.5a2.121 2.121 0 0 1 3 3L7 19l-4 1 1-4L16.5 3.5z"></path>
                                  </svg>

                                  <svg
                                    stroke="currentColor"
                                    fill="currentColor"
                                    stroke-width="0"
                                    viewBox="0 0 24 24"
                                    class="text-[#444] hover:text-[#c20000]  cursor-pointer delay-200 transition-all text-[18px]"
                                    height="1em"
                                    width="1em"
                                    xmlns="http://www.w3.org/2000/svg"
                                  >
                                    <path
                                      fill="none"
                                      d="M0 0h24v24H0V0z"
                                    ></path>
                                    <path d="M6 19c0 1.1.9 2 2 2h8c1.1 0 2-.9 2-2V7H6v12zM8 9h8v10H8V9zm7.5-5-1-1h-5l-1 1H5v2h14V4z"></path>
                                  </svg>
                                </td>
                              </tr>
                              <tr
                                title="EcoWave Energy"
                                className="border  border-b-[#ebebeb] border-t-[#fff] border-r-[#fff] border-l-[#fff]"
                              >
                                <td className="py-3 px-2 text-sm text-[#333]">
                                  {" "}
                                  010
                                </td>
                                <td className="py-3 px-2  text-sm text-[#333] font-semibold">
                                  EcoWave Energy
                                </td>
                                <td className="py-3 px-2  text-sm text-[#333] ">
                                  22 Feb 2024
                                </td>
                                <td className="py-3 px-2  text-sm text-[#333] ">
                                  <div className="py-1 px-2 text-center bg-[#b4ff8e] text-[#0b6c00] rounded-full w-16">
                                    paid
                                  </div>
                                </td>
                                <td className="py-3 px-4  text-right text-sm text-[#333] ">
                                  $555.6
                                </td>
                                <td className="py-4 px-4  flex  space-x-12 text-sm text-[#333] ">
                                  <svg
                                    stroke="currentColor"
                                    fill="currentColor"
                                    stroke-width="0"
                                    viewBox="0 0 16 16"
                                    height="1em"
                                    width="1em"
                                    xmlns="http://www.w3.org/2000/svg"
                                    class=" text-[#008cff] hover:text-[#0000ca]  cursor-pointer delay-200 transition-all text-[16px]"
                                  >
                                    <path d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8M1.173 8a13 13 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5s3.879 1.168 5.168 2.457A13 13 0 0 1 14.828 8q-.086.13-.195.288c-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5s-3.879-1.168-5.168-2.457A13 13 0 0 1 1.172 8z"></path>
                                    <path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5M4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0"></path>
                                  </svg>

                                  <svg
                                    stroke="currentColor"
                                    fill="none"
                                    stroke-width="2"
                                    viewBox="0 0 24 24"
                                    stroke-linecap="round"
                                    stroke-linejoin="round"
                                    height="1em"
                                    width="1em"
                                    xmlns="http://www.w3.org/2000/svg"
                                    class="text-[#444] hover:text-[#0b6c00]  cursor-pointer delay-200 transition-all text-[16px]"
                                  >
                                    <path d="M12 20h9"></path>
                                    <path d="M16.5 3.5a2.121 2.121 0 0 1 3 3L7 19l-4 1 1-4L16.5 3.5z"></path>
                                  </svg>

                                  <svg
                                    stroke="currentColor"
                                    fill="currentColor"
                                    stroke-width="0"
                                    viewBox="0 0 24 24"
                                    class="text-[#444] hover:text-[#c20000]  cursor-pointer delay-200 transition-all text-[18px]"
                                    height="1em"
                                    width="1em"
                                    xmlns="http://www.w3.org/2000/svg"
                                  >
                                    <path
                                      fill="none"
                                      d="M0 0h24v24H0V0z"
                                    ></path>
                                    <path d="M6 19c0 1.1.9 2 2 2h8c1.1 0 2-.9 2-2V7H6v12zM8 9h8v10H8V9zm7.5-5-1-1h-5l-1 1H5v2h14V4z"></path>
                                  </svg>
                                </td>
                              </tr>
                            </tbody>
                          </table>
                        </div>
                      </div>
                    </div>
                  </section>
                </div>
              </>
            )}
          </div>
        </div>

        <div>
          {/* <h2>Related Components</h2>  */}
          <h2
            data-aos="fade-up"
            className={`title-font pt-10 pb-6 text-center text-secondary text-2xl font-semibold`}
          >
            Related Components
          </h2>

          <div>
            <div
              className={` grid lg:grid-cols-3 lge:grid-cols-3 md:grid-cols-2 mdsm:grid-cols-2 sm:grid-cols-1 sm:px-2 gap-5`}
            >
              {reelatedComp?.map((v, i) => {
                return (
                  <HomeCard
                    title={v?.title}
                    img={v?.image}
                    tag={v?.section}
                    link={v?.link}
                  />
                );
              })}
            </div>
          </div>

          <div></div>
        </div>
      </div>
      <Footer />
    </div>
  );
}
